spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///ruoyi?serverTimezone=Asia/Shanghai&useSSL=false
  redis:
    host: 114.132.51.96
    password: 123456

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*.xml
server:
  port: 8090


